### ISSUE TITLE
Should we refork and rebase to preserve the origin's commit history?

### ISSUE THREAD

**Issue by glennsl** [BuckleTypes/bs-containers#7]
So I noticed the commit history has been severed from its origin. Should we do a refork and rebase to preserve the history before we get too far into it?

**Comment by dorafmon** [comment]
I think the final result of this repo will be dramatically different from ocaml-containers per the Roadmap and discussion we had, so probably we should treat this repo as a fresh start based on the ocaml-containers, but with different design goals (targeted at Reason/Js community, optimised for the BS runtime etc.)
